### PR TITLE
Fix lockscreen appearance

### PR DESCRIPTION
**Pull request by silvanfischer**
The keyguard should not be dismissed on these screen as it could cause the opposite and add the keyguard again to these screens. `showOnLockScreen` is actually enough to make it appear.

### CODE REVIEW

**Comment by saghul** [comment]
Thanks for the patch! Can you please go a bit into the details on what you are fixing and how?

**Comment by Holofox** [comment]
@saghul, i think the fix is to be able to show [WrapperJitsiMeetActivity] on locked screen. Now if you try to open [WrapperJitsiMeetActivity] when the screen is locked, the user will not see it. This is necessary when we want to show a full-screen notification and connect the user to a call. Now we get the opposite effect, when we try to open [WrapperJitsiMeetActivity], the screen will lock.

@silvanfischer, i see code formatting in some places, I think we need to remove unnecessary changes and focus on the problem.

**Comment by saghul** [comment]
Got it.

Indeed please skip the unnecessary formatting changes and we can merge this.

**Comment by Calinteodor** [comment]
@silvanfischer Can you update this with all of the above so we can ✅ and merge it? Thank you!

**Pull request merged**
